server:
  port: 80
#  port: 443
#  ssl:
#    key-store: classpath:keystore/keystore.p12
#    key-store-type: PKCS12
#    key-store-password: crew1207

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
  jpa:
    hibernate: update
    properties:
      hibername:
        show_sql: true
        format_sql: true
